FROM python:3.6
RUN pip install requests -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple requests
RUN pip install requests -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple BeautifulSoup4
